// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgRLbWVTTAWHz_NUAsaNamb-cVPRSvGI',
    appId: '1:1065762162388:web:aca326a039e141ae685d41',
    messagingSenderId: '1065762162388',
    projectId: 'ats-resume-98571',
    authDomain: 'ats-resume-98571.firebaseapp.com',
    storageBucket: 'ats-resume-98571.firebasestorage.app',
    measurementId: 'G-2BL9RCMGK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaquPhjLizbhA4_XjtJDAyYwWS9QpIyVk',
    appId: '1:1065762162388:android:3f9b019060ea5079685d41',
    messagingSenderId: '1065762162388',
    projectId: 'ats-resume-98571',
    storageBucket: 'ats-resume-98571.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-eTwwDRex2KpZ0o3YttxMAReZ1NWwTI',
    appId: '1:1065762162388:ios:09099984f1fc76ea685d41',
    messagingSenderId: '1065762162388',
    projectId: 'ats-resume-98571',
    storageBucket: 'ats-resume-98571.firebasestorage.app',
    iosBundleId: 'com.example.resumeBuilder',
  );
}